USE DATABASE NYC_TAXI_DB;
USE SCHEMA RAW;
USE WAREHOUSE NYC_TAXI_WH;

TRUNCATE TABLE RAW.YELLOW_TAXI_2026_H1;
COPY INTO RAW.YELLOW_TAXI_2026_H1
FROM @TAXI_STAGE
FILE_FORMAT = (TYPE = PARQUET USE_LOGICAL_TYPE = TRUE)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;