USE DATABASE NYC_TAXI_DB;
USE SCHEMA RAW;
USE WAREHOUSE NYC_TAXI_WH;

SELECT COUNT(*) AS total_rows
FROM RAW.YELLOW_TAXI_2026_H1;

SELECT
    month,
    COUNT(*) AS row_count
FROM RAW.YELLOW_TAXI_2026_H1
GROUP BY month
ORDER BY month;

SELECT *
FROM RAW.YELLOW_TAXI_2026_H1
LIMIT 5;